// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hart_OP_AL_32I (
        ap_ready,
        opcode_val,
        func7_val,
        func3_val,
        op1_val,
        op2_val,
        ap_return
);


output   ap_ready;
input  [5:0] opcode_val;
input  [6:0] func7_val;
input  [2:0] func3_val;
input  [30:0] op1_val;
input  [30:0] op2_val;
output  [31:0] ap_return;

wire   [30:0] grp_fu_262_p2;
reg   [30:0] ap_phi_mux_rd_val_9_phi_fu_85_p52;
wire   [5:0] opcode_val_read_read_fu_76_p2;
wire   [2:0] func3_val_read_read_fu_64_p2;
wire   [6:0] func7_val_read_read_fu_70_p2;
wire   [30:0] grp_fu_226_p2;
wire   [30:0] grp_fu_234_p2;
wire   [30:0] zext_ln8_1_fu_334_p1;
wire   [30:0] zext_ln8_fu_339_p1;
wire   [30:0] rd_val_2_fu_352_p2;
wire   [30:0] grp_fu_254_p2;
wire   [30:0] rd_val_16_fu_308_p2;
wire   [30:0] trunc_ln8_1_fu_329_p1;
wire   [30:0] rd_val_14_fu_370_p2;
wire   [30:0] grp_fu_283_p2;
wire   [0:0] grp_fu_270_p3;
wire   [30:0] ashr_ln29_fu_363_p2;
wire   [30:0] zext_ln8_3_fu_388_p1;
wire   [30:0] zext_ln8_2_fu_393_p1;
wire   [30:0] trunc_ln20_1_fu_383_p1;
wire   [30:0] ashr_ln16_fu_409_p2;
wire   [30:0] shl_ln16_fu_402_p2;
reg   [0:0] ap_phi_mux_error_phi_fu_146_p52;
wire  signed [30:0] grp_fu_226_p0;
wire  signed [30:0] grp_fu_226_p1;
wire  signed [30:0] grp_fu_234_p0;
wire  signed [30:0] grp_fu_234_p1;
wire  signed [30:0] grp_fu_242_p0;
wire  signed [30:0] grp_fu_242_p1;
wire  signed [30:0] grp_fu_248_p0;
wire  signed [30:0] grp_fu_248_p1;
wire  signed [30:0] grp_fu_254_p0;
wire  signed [30:0] grp_fu_254_p1;
wire  signed [30:0] grp_fu_262_p0;
wire  signed [30:0] grp_fu_262_p1;
wire  signed [31:0] op2_val_cast3_fu_291_p1;
wire  signed [30:0] grp_fu_277_p1;
wire  signed [30:0] grp_fu_283_p0;
wire   [30:0] grp_fu_277_p2;
wire  signed [30:0] op2_val_cast3_fu_291_p0;
wire  signed [30:0] op1_val_cast_fu_296_p0;
wire  signed [30:0] trunc_ln46_fu_300_p0;
wire   [4:0] trunc_ln46_fu_300_p1;
wire  signed [30:0] rd_val_16_fu_308_p0;
wire   [30:0] trunc_ln46cast_fu_304_p1;
wire  signed [30:0] trunc_ln45_fu_315_p0;
wire   [4:0] trunc_ln45_fu_315_p1;
wire  signed [31:0] op1_val_cast_fu_296_p1;
wire   [31:0] zext_ln45_fu_319_p1;
wire   [31:0] rd_val_15_fu_323_p2;
wire   [0:0] grp_fu_242_p2;
wire   [0:0] grp_fu_248_p2;
wire  signed [30:0] trunc_ln39_fu_344_p0;
wire   [4:0] trunc_ln39_fu_344_p1;
wire  signed [30:0] rd_val_2_fu_352_p0;
wire   [30:0] trunc_ln39cast_fu_348_p1;
wire  signed [30:0] ashr_ln29_fu_363_p0;
wire   [30:0] op2_val_cast3cast23_fu_359_p1;
wire  signed [30:0] rd_val_14_fu_370_p0;
wire  signed [30:0] rd_val_14_fu_370_p1;
wire   [31:0] lshr_ln20_fu_377_p2;
wire  signed [30:0] shl_ln16_fu_402_p0;
wire   [30:0] op2_val_cast3cast_fu_398_p1;
wire  signed [30:0] ashr_ln16_fu_409_p0;
wire    ap_ce_reg;

always @ (*) begin
    if (((~(func3_val_read_read_fu_64_p2 == 3'd5) & ~(func3_val_read_read_fu_64_p2 == 3'd0) & (func7_val_read_read_fu_70_p2 == 7'd32) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | (~(func7_val_read_read_fu_70_p2 == 7'd32) & ~(func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | (~(func7_val_read_read_fu_70_p2 == 7'd32) & ~(func7_val_read_read_fu_70_p2 == 7'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | (~(opcode_val_read_read_fu_76_p2 == 6'd51) & ~(opcode_val_read_read_fu_76_p2 == 6'd19)))) begin
        ap_phi_mux_error_phi_fu_146_p52 = 1'd1;
    end else if ((((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func3_val_read_read_fu_64_p2 
    == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func3_val_read_read_fu_64_p2 == 3'd2) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func3_val_read_read_fu_64_p2 == 3'd3) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func3_val_read_read_fu_64_p2 == 3'd4) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func3_val_read_read_fu_64_p2 == 3'd6) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd2) & (opcode_val_read_read_fu_76_p2 == 
    6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd3) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd4) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd6) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd7) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func3_val_read_read_fu_64_p2 == 3'd7) & (opcode_val_read_read_fu_76_p2 == 6'd19)))) begin
        ap_phi_mux_error_phi_fu_146_p52 = 1'd0;
    end else begin
        ap_phi_mux_error_phi_fu_146_p52 = 'bx;
    end
end

always @ (*) begin
    if (((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = shl_ln16_fu_402_p2;
    end else if (((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = ashr_ln16_fu_409_p2;
    end else if (((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = trunc_ln20_1_fu_383_p1;
    end else if (((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd2) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = zext_ln8_2_fu_393_p1;
    end else if (((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd3) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = zext_ln8_3_fu_388_p1;
    end else if (((grp_fu_270_p3 == 1'd0) & (func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = ashr_ln29_fu_363_p2;
    end else if ((((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((grp_fu_270_p3 == 1'd1) & (func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd51)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = grp_fu_283_p2;
    end else if (((func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = rd_val_14_fu_370_p2;
    end else if (((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = trunc_ln8_1_fu_329_p1;
    end else if (((func7_val_read_read_fu_70_p2 == 7'd32) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = rd_val_16_fu_308_p2;
    end else if ((((func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = grp_fu_254_p2;
    end else if (((func3_val_read_read_fu_64_p2 == 3'd1) & (opcode_val_read_read_fu_76_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = rd_val_2_fu_352_p2;
    end else if (((func3_val_read_read_fu_64_p2 == 3'd2) & (opcode_val_read_read_fu_76_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = zext_ln8_fu_339_p1;
    end else if (((func3_val_read_read_fu_64_p2 == 3'd3) & (opcode_val_read_read_fu_76_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = zext_ln8_1_fu_334_p1;
    end else if ((((func3_val_read_read_fu_64_p2 == 3'd4) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd4) & (opcode_val_read_read_fu_76_p2 == 6'd51)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = grp_fu_234_p2;
    end else if ((((func3_val_read_read_fu_64_p2 == 3'd6) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | ((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd6) & (opcode_val_read_read_fu_76_p2 == 6'd51)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = grp_fu_226_p2;
    end else if (((~(func3_val_read_read_fu_64_p2 == 3'd5) & ~(func3_val_read_read_fu_64_p2 == 3'd0) & (func7_val_read_read_fu_70_p2 == 7'd32) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | (~(func7_val_read_read_fu_70_p2 == 7'd32) & ~(func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd5) & (opcode_val_read_read_fu_76_p2 == 6'd19)) | (~(func7_val_read_read_fu_70_p2 == 7'd32) & ~(func7_val_read_read_fu_70_p2 == 7'd0) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | (~(opcode_val_read_read_fu_76_p2 == 6'd51) & ~(opcode_val_read_read_fu_76_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = 31'd0;
    end else if ((((func7_val_read_read_fu_70_p2 == 7'd0) & (func3_val_read_read_fu_64_p2 == 3'd7) & (opcode_val_read_read_fu_76_p2 == 6'd51)) | ((func3_val_read_read_fu_64_p2 == 3'd7) & (opcode_val_read_read_fu_76_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = grp_fu_262_p2;
    end else begin
        ap_phi_mux_rd_val_9_phi_fu_85_p52 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ashr_ln16_fu_409_p2 = $signed(ashr_ln16_fu_409_p0) >>> grp_fu_277_p2;

assign ashr_ln29_fu_363_p2 = $signed(ashr_ln29_fu_363_p0) >>> op2_val_cast3cast23_fu_359_p1;

assign grp_fu_226_p0 = op2_val;

assign grp_fu_226_p1 = op1_val;

assign grp_fu_226_p2 = (grp_fu_226_p1 | grp_fu_226_p0);

assign grp_fu_234_p0 = op2_val;

assign grp_fu_234_p1 = op1_val;

assign grp_fu_234_p2 = (grp_fu_234_p1 ^ grp_fu_234_p0);

assign grp_fu_242_p0 = op1_val;

assign grp_fu_242_p1 = op2_val;

assign grp_fu_242_p2 = ((grp_fu_242_p0 < grp_fu_242_p1) ? 1'b1 : 1'b0);

assign grp_fu_248_p0 = op1_val;

assign grp_fu_248_p1 = op2_val;

assign grp_fu_248_p2 = (($signed(grp_fu_248_p0) < $signed(grp_fu_248_p1)) ? 1'b1 : 1'b0);

assign grp_fu_254_p0 = op2_val;

assign grp_fu_254_p1 = op1_val;

assign grp_fu_254_p2 = ($signed(grp_fu_254_p0) + $signed(grp_fu_254_p1));

assign grp_fu_262_p0 = op2_val;

assign grp_fu_262_p1 = op1_val;

assign grp_fu_262_p2 = (grp_fu_262_p1 & grp_fu_262_p0);

assign grp_fu_270_p3 = op2_val_cast3_fu_291_p1[32'd31];

assign grp_fu_277_p1 = op2_val;

assign grp_fu_277_p2 = ($signed(31'd0) - $signed(grp_fu_277_p1));

assign grp_fu_283_p0 = op1_val;

assign grp_fu_283_p2 = grp_fu_283_p0 << grp_fu_277_p2;

assign lshr_ln20_fu_377_p2 = op1_val_cast_fu_296_p1 >> op2_val_cast3_fu_291_p1;

assign op1_val_cast_fu_296_p1 = op1_val_cast_fu_296_p0;

assign op2_val_cast3_fu_291_p1 = op2_val_cast3_fu_291_p0;

assign op2_val_cast3cast23_fu_359_p1 = op2_val_cast3_fu_291_p1[30:0];

assign op2_val_cast3cast_fu_398_p1 = op2_val_cast3_fu_291_p1[30:0];

assign rd_val_14_fu_370_p2 = ($signed(rd_val_14_fu_370_p0) - $signed(rd_val_14_fu_370_p1));

assign rd_val_15_fu_323_p2 = op1_val_cast_fu_296_p1 >> zext_ln45_fu_319_p1;

assign rd_val_16_fu_308_p2 = $signed(rd_val_16_fu_308_p0) >>> trunc_ln46cast_fu_304_p1;

assign rd_val_2_fu_352_p2 = rd_val_2_fu_352_p0 << trunc_ln39cast_fu_348_p1;

assign shl_ln16_fu_402_p2 = shl_ln16_fu_402_p0 << op2_val_cast3cast_fu_398_p1;

assign trunc_ln20_1_fu_383_p1 = lshr_ln20_fu_377_p2[30:0];

assign trunc_ln39_fu_344_p1 = trunc_ln39_fu_344_p0[4:0];

assign trunc_ln39cast_fu_348_p1 = trunc_ln39_fu_344_p1;

assign trunc_ln45_fu_315_p1 = trunc_ln45_fu_315_p0[4:0];

assign trunc_ln46_fu_300_p1 = trunc_ln46_fu_300_p0[4:0];

assign trunc_ln46cast_fu_304_p1 = trunc_ln46_fu_300_p1;

assign trunc_ln8_1_fu_329_p1 = rd_val_15_fu_323_p2[30:0];

assign zext_ln45_fu_319_p1 = trunc_ln45_fu_315_p1;

assign zext_ln8_1_fu_334_p1 = grp_fu_242_p2;

assign zext_ln8_2_fu_393_p1 = grp_fu_248_p2;

assign zext_ln8_3_fu_388_p1 = grp_fu_242_p2;

assign zext_ln8_fu_339_p1 = grp_fu_248_p2;

assign ap_return = {{ap_phi_mux_rd_val_9_phi_fu_85_p52}, {ap_phi_mux_error_phi_fu_146_p52}};

assign ashr_ln16_fu_409_p0 = op1_val;

assign ashr_ln29_fu_363_p0 = op1_val;

assign func3_val_read_read_fu_64_p2 = func3_val;

assign func7_val_read_read_fu_70_p2 = func7_val;

assign op1_val_cast_fu_296_p0 = op1_val;

assign op2_val_cast3_fu_291_p0 = op2_val;

assign opcode_val_read_read_fu_76_p2 = opcode_val;

assign rd_val_14_fu_370_p0 = op1_val;

assign rd_val_14_fu_370_p1 = op2_val;

assign rd_val_16_fu_308_p0 = op1_val;

assign rd_val_2_fu_352_p0 = op1_val;

assign shl_ln16_fu_402_p0 = op1_val;

assign trunc_ln39_fu_344_p0 = op2_val;

assign trunc_ln45_fu_315_p0 = op2_val;

assign trunc_ln46_fu_300_p0 = op2_val;

endmodule //hart_OP_AL_32I
